config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView

from django.conf.urls.i18n import i18n_patterns

admin.autodiscover()

urlpatterns = [

    url(r'^accounts/', include('allauth.urls')),
    url(r'^', include('hes.urls', namespace="hes")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', 'django.views.defaults.bad_request'),
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
    ]

# Mezzanine

# Add the urlpatterns for any custom Django applications here.
# You can also change the ``home`` view to add your own functionality
# to the project's homepage.

from django.conf.urls import patterns
from mezzanine.conf import settings as msettings
from mezzanine.core.views import direct_to_template

urlpatterns += i18n_patterns("",
    # Change the admin prefix here to use an alternate URL for the
    # admin interface, which would be marginally more secure.
        ("^admin/", include(admin.site.urls)),
    )

if msettings.USE_MODELTRANSLATION:
    urlpatterns += patterns('',
        url('^i18n/$', 'django.views.i18n.set_language', name='set_language'),
    )

urlpatterns += patterns('',
    # Cartridge URLs.
    ("^shop/", include("cartridge.shop.urls")),
    url("^account/orders/$", "cartridge.shop.views.order_history",
        name="shop_order_history"),

    url("^$", direct_to_template, {"template": "hes/index.html"}, name="home"),

    # If you'd like more granular control over the patterns in
    # ``mezzanine.urls``, go right ahead and take the parts you want
    # from it, and use them directly below instead of using
    # ``mezzanine.urls``.
    ("^", include("mezzanine.urls")),
)

# Adds ``STATIC_URL`` to the context of error pages, so that error
# pages can use JS, CSS and images.
handler404 = "mezzanine.core.views.page_not_found"
handler500 = "mezzanine.core.views.server_error"

hes/urls.py
__author__ = 'dave'
from django.conf.urls import url, include
from mezzanine.core.views import direct_to_template
from .views import ajax, coming_soon

urlpatterns = [

    url("^about$", direct_to_template, {"template": "hes/about-us.html"}, name="about-us"),
    url("^signup\.html$", direct_to_template, {"template": "hes/old_signup.html"}, name="signup"),
    url("^forgot-password\.html$", direct_to_template, {"template": "hes/forgot-password.html"}, name="forgot-password"),
    url("^account$", direct_to_template, {"template": "users/account-home.html"}, name="account-home"),
    url("^account-close$", direct_to_template, {"template": "users/account-close.html"}, name="account-close"),
    url("^account-saved-search$", direct_to_template, {"template": "users/account-saved-search.html"}, name="account-saved-search"),
    url("^account-pending-approval-ads$", direct_to_template, {"template": "users/account-pending-approval-ads.html"}, name="account-pending-approval-ads"),
    url("^account-favourite-ads$", direct_to_template, {"template": "users/account-favourite-ads.html"}, name="account-favorite-ads"),
    url("^item-detail$", direct_to_template, {"template": "hes/ads-details.html"}, name="item-detail"),
    url("^account-archived-ads$", direct_to_template, {"template": "users/account-archived-ads.html"}, name="account-archived-ads"),
    url("^blank-page$", direct_to_template, {"template": "hes/blank-page.html"}, name="blank-page"),
    url("^posting-success$", direct_to_template, {"template": "hes/posting-success.html"}, name="posting-success"),
    url("^category$", direct_to_template, {"template": "hes/category.html"}, name="category"),
    url("^ajax/(?P<ajax_code>[1-3])$", ajax, name="ajax"),
    url("^sub-category-sub-location$", direct_to_template, {"template": "hes/sub-category-sub-location.html"}, name="sub-category"),
    url("^coming-soon$", coming_soon, name="coming-soon"),
    url("^contact$", direct_to_template, {"template": "hes/contact.html"}, name="contact"),
    url("^faq$", direct_to_template, {"template": "hes/faq.html"}, name="faq"),

    #User management
    url(r'^users/', include("hes.users.urls", namespace="users")),
]

hes/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url
from mezzanine.core.views import direct_to_template

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(regex=r'^$', view=views.UserListView.as_view(), name='list'),

    # URL pattern for the UserRedirectView
    url(regex=r'^~redirect/$', view=views.UserRedirectView.as_view(), name='redirect'),

    # URL pattern for the UserDetailView
    url(regex=r'^(?P<username>[\w.@+-]+)/$', view=views.UserDetailView.as_view(), name='detail'),

    # URL pattern for the UserUpdateView
    url(regex=r'^~update/$', view=views.UserUpdateView.as_view(), name='update'),
]

hes/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
# from django.db import models
# from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    def __unicode__(self):
        return self.username

hes/forms.py
__author__ = 'dave'

from django import forms
from crispy_forms.helper import FormHelper
from allauth.account.forms import LoginForm


# Reusable crispy forms for the website
# TODO implement the extended login form at a later time

class ExtendedLoginForm(LoginForm):

    def __init__(self, *args, **kwargs):
        self.helper = FormHelper()
        self.helper.form_method = 'POST'

        self.username = forms.CharField(label="Username", required=True)
        super.__init__()

hes/users/forms.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django import forms

from .models import User


class UserForm(forms.ModelForm):

    class Meta:
        # Set this form to use the User model.
        model = User

        # Constrain the UserForm to just these fields.
        fields = ("first_name", "last_name")

hes/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from braces.views import LoginRequiredMixin

from .forms import UserForm
from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("hes:users:detail",
                       kwargs={"username": self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    form_class = UserForm

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("hes:users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = "username"
    slug_url_kwarg = "username"

hes/views.py
__author__ = 'dave'
from django.shortcuts import render

def ajax(request, ajax_code):
    return render(request=request, template_name="hes/ajax/%s.html" % ajax_code, context={})

def coming_soon(request):
    return render(request=request, template_name="hes/coming-soon.html", context={})

hes/templates/hes/ads-details.html
{% extends "hes/base.html" %}

{% load staticfiles %}

{% block body_container %}
  <div class="main-container">
    <div class="container">
      <ol class="breadcrumb pull-left">
        <li><a href="/"><i class="icon-home fa"></i></a></li>
        <li><a href="{% url "hes:category" %}">All Ads</a></li>
        <li><a href="{% url "hes:sub-category" %}">Electronics</a></li>
        <li class="active">Mobile Phones</li>
      </ol>
      <div class="pull-right backtolist"><a href="{% url "hes:sub-category" %}"> <i class="fa fa-angle-double-left"></i> Back to Results</a></div>
    </div>
    <div class="container">
      <div class="row">
        <div class="col-sm-9 page-content col-thin-right">
          <div class="inner inner-box ads-details-wrapper">
            <h2> Xperia™ C3 Dual available <small class="label label-default adlistingtype">Company ad</small> </h2>
            <span class="info-row"> <span class="date"><i class=" icon-clock"> </i> Today 1:21 pm </span> - <span class="category">Electronics </span>- <span class="item-location"><i class="fa fa-map-marker"></i> New York </span> </span>
            <div class="ads-image">
              <h1 class="pricetag"> $25</h1>
              <ul class="bxslider">
                <li><img src="{% static "hes/images/item/tp-big/Image00014.jpg" %}" alt="img" /></li>
                <li><img src="{% static "hes/images/item/tp-big/Image00015.jpg" %}" alt="img" /></li>
                <li><img src="{% static "hes/images/item/tp-big/Image00013.jpg" %}" alt="img" /></li>
              </ul>
              <div id="bx-pager"> <a class="thumb-item-link" data-slide-index="0" href=""><img src="{% static "hes/images/item/tp/Image00014.jpg" %}" alt="img" /></a> <a class="thumb-item-link"  data-slide-index="1" href=""><img src="{% static "hes/images/item/tp/Image00015.jpg" %}" alt="img" /></a> <a class="thumb-item-link"  data-slide-index="2" href=""><img src="{% static "hes/images/item/tp/Image00013.jpg" %}" alt="img" /></a> </div>
            </div>
            <!--ads-image-->
            
            <div class="Ads-Details">
              <h5 class="list-title"><strong>Ad Details</strong></h5>
              <div class="row">
                <div class="ads-details-info col-md-8">
                  <p>Sony Xperia C3 Dual smartphone with 5.50-inch 720x1280 display powered by 1.2GHz processor alongside 1GB RAM and 8-megapixel rear camera. </p>
                  <h4>Camera and video</h4>
                  <ul class="list-circle">
                    <li>5 MP Front-facing camera (720p)</li>
                    <li>Front flash LED</li>
                    <li>Wide view front camera</li>
                    <li>8 MP camera with auto focus</li>
                    <li>HD video recording 1080 p</li>
                    <li>Sony Exmor RS for mobile image sensor</li>
                    <li>HDR (High Dynamic Range) for photos and videos</li>
                    <li>Pulsed LED flash</li>
                    <li>16x digital zoom</li>
                    <li>Superior Auto – automatic scene selection</li>
                    <li>Geotagging – add location info to your photos</li>
                    <li>Object tracking – lock focus on a specific object</li>
                    <li>Red-eye reduction</li>
                    <li>Image capture, supported file format: JPEG</li>
                    <li>Image playback, supported file formats: BMP, GIF, JPEG, PNG; WebP</li>
                    <li>Video capture, supported file formats: 3GPP, MP4</li>
                    <li>Video playback, supported file formats: 3GPP, MP4, M4V, AvI, XVID, WEBM</li>
                  </ul>
                  <h4>Networks</h4>
                  <ul>
                    <li>GSM GPRS/EDGE (2G)</li>
                    <li>UMTS HSPA (3G)</li>
                    <li>LTE (4G)</li>
                  </ul>
                </div>
                <div class="col-md-4">
                  <aside class="panel panel-body panel-details">
                    <ul>
                      <li>
                        <p class=" no-margin "><strong>Price:</strong> $ 2,45</p>
                      </li>
                      <li>
                        <p class="no-margin"><strong>Type:</strong> Mobile Mobiles,For sale</p>
                      </li>
                      <li>
                        <p class="no-margin"><strong>Location:</strong> New York </p>
                      </li>
                      <li>
                        <p class=" no-margin "><strong>Condition:</strong> New</p>
                      </li>
                      <li>
                        <p class="no-margin"><strong>Brand:</strong> Sony</p>
                      </li>
                    </ul>
                  </aside>
                  <div class="ads-action">
                    <ul class="list-border">
                      <li><a  href="#" > <i class=" fa fa-user"></i> More ads by User </a> </li>
                      <li><a  href="#" > <i class=" fa fa-heart"></i> Save ad </a> </li>
                      <li><a  href="#" > <i class="fa fa-share-alt"></i> Share ad </a> </li>
                      <li><a   href="#reportAdvertiser" data-toggle="modal"> <i class="fa icon-info-circled-alt"></i> Report abuse </a> </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div class="content-footer text-left"> <a class="btn  btn-default" data-toggle="modal" href="#contactAdvertiser"><i class=" icon-mail-2"></i> Send a message </a> <a class="btn  btn-info" ><i class=" icon-phone-1"></i> 01680 531 352 </a> </div>
            </div>
          </div>
          <!--/.ads-details-wrapper--> 
          
        </div>
        <!--/.page-content-->
        
        <div class="col-sm-3  page-sidebar-right">
          <aside>
            <div class="panel sidebar-panel panel-contact-seller">
              <div class="panel-heading">Contact Seller</div>
              <div class="panel-content user-info">
                <div class="panel-body text-center">
                  <div class="seller-info">
                    <h3 class="no-margin">Richard Aki</h3>
                    <p>Location: <strong>New York</strong></p>
                    <p> Joined: <strong>12 Mar 2009</strong></p>
                  </div>
                  <div class="user-ads-action"> <a href="#contactAdvertiser" data-toggle="modal" class="btn   btn-default btn-block"><i class=" icon-mail-2"></i> Send a message </a> <a class="btn  btn-info btn-block"><i class=" icon-phone-1"></i> 01680 531 352 </a> </div>
                </div>
              </div>
            </div>
            <div class="panel sidebar-panel">
              <div class="panel-heading">Safety Tips for Buyers</div>
              <div class="panel-content">
                <div class="panel-body text-left">
                  <ul class="list-check">
                    <li> Meet seller at a public place </li>
                    <li> Check the item before you buy</li>
                    <li> Pay only after collecting the item</li>
                  </ul>
                  <p><a class="pull-right" href="#"> Know more <i class="fa fa-angle-double-right"></i> </a></p>
                </div>
              </div>
            </div>
            <!--/.categories-list--> 
          </aside>
        </div>
        <!--/.page-side-bar--> 
      </div>
    </div>
  </div>
  <!-- /.main-container -->


<!-- Modal contactAdvertiser -->

<div class="modal fade" id="reportAdvertiser" tabindex="-1" role="dialog" >
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" ><i class="fa icon-info-circled-alt"></i> There's something wrong with this  ads? </h4>
      </div>
      <div class="modal-body">
        <form role="form">
          <div class="form-group">
            <label for="report-reason" class="control-label">Reason:</label>
            <select name="report-reason" id="report-reason" class="form-control">
              <option value="">Select a reason</option>
              <option value="soldUnavailable">Item unavailable</option>
              <option value="fraud">Fraud</option>
              <option value="duplicate">Duplicate</option>
              <option value="spam">Spam</option>
              <option value="wrongCategory">Wrong category</option>
              <option value="other">Other</option>
            </select>
          </div>
          <div class="form-group">
            <label for="recipient-email" class="control-label">Your E-mail:</label>
            <input type="text"  name="email" maxlength="60" class="form-control" id="recipient-email">
          </div>
          <div class="form-group">
            <label for="message-text2" class="control-label">Message <span class="text-count">(300) </span>:</label>
            <textarea class="form-control" id="message-text2"></textarea>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="button" class="btn btn-primary">Send Report</button>
      </div>
    </div>
  </div>
</div>

<!-- /.modal --> 

<!-- Modal contactAdvertiser -->

<div class="modal fade" id="contactAdvertiser" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title"><i class=" icon-mail-2"></i> Contact advertiser </h4>
      </div>
      <div class="modal-body">
        <form role="form">
          <div class="form-group">
            <label for="recipient-name" class="control-label">Name:</label>
            <input class="form-control required" id="recipient-name" placeholder="Your name" data-placement="top" data-trigger="manual" data-content="Must be at least 3 characters long, and must only contain letters." type="text">
          </div>
          <div class="form-group">
            <label for="sender-email" class="control-label">E-mail:</label>
            <input id="sender-email" type="text" data-content="Must be a valid e-mail address (user@gmail.com)" data-trigger="manual" data-placement="top" placeholder="email@you.com" class="form-control email">
          </div>
          <div class="form-group">
            <label for="recipient-Phone-Number"  class="control-label">Phone Number:</label>
            <input type="text"  maxlength="60" class="form-control" id="recipient-Phone-Number">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Message <span class="text-count">(300) </span>:</label>
            <textarea class="form-control" id="message-text"  placeholder="Your message here.." data-placement="top" data-trigger="manual"></textarea>
          </div>
          <div class="form-group">
            <p class="help-block pull-left text-danger hide" id="form-error">&nbsp; The form is not valid. </p>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
        <button type="submit" class="btn btn-success pull-right">Send message!</button>
      </div>
    </div>
  </div>
</div>

<!-- /.modal -->
{% endblock body_container %}

{% block extra_js %}
<!-- bxSlider Javascript file -->
<script src="{% static "hes/plugins/bxslider/jquery.bxslider.min.js" %}"></script>
<script>
$('.bxslider').bxSlider({
  pagerCustom: '#bx-pager'
});

</script>
{% endblock extra_js %}


hes/templates/hes/base.html
<!DOCTYPE html>

<html lang="{{ LANGUAGE_CODE }}"{% if LANGUAGE_BIDI %} dir="rtl"{% endif %}>
{% load pages_tags mezzanine_tags i18n staticfiles account %}

<head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="{% block meta_keywords %}{% endblock %}">
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <title>
        {% block meta_title %}{% endblock %}{% if settings.SITE_TITLE %} | {{ settings.SITE_TITLE }}{% endif %}
    </title>

    <!-- Fav and touch icons -->
    <link rel="apple-touch-icon-precomposed" sizes="144x144"
          href="{% static "hes/ico/apple-touch-icon-144-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="114x114"
          href="{% static "hes/ico/apple-touch-icon-114-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" sizes="72x72"
          href="{% static "hes/ico/apple-touch-icon-72-precomposed.png" %}">
    <link rel="apple-touch-icon-precomposed" href="{% static "hes/ico/apple-touch-icon-57-precomposed.png" %}">
    <link rel="shortcut icon" href="{% static "hes/ico/favicon.png" %}">

    {% ifinstalled mezzanine.blog %}
        <link rel="alternate" type="application/rss+xml" title="RSS" href="{% url "blog_post_feed" "rss" %}">
        <link rel="alternate" type="application/atom+xml" title="Atom" href="{% url "blog_post_feed" "atom" %}">
    {% endifinstalled %}

    {% compress css %}
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">

        {# Custom Styling #}
        <link rel="stylesheet" href="{% static "hes/css/style.css" %}">
        {#    Style needed for carousel slider #}
        <link rel="stylesheet" href="{% static "hes/css/owl.carousel.css" %}">
        <link rel="stylesheet" href="{% static "hes/css/owl.theme.css" %}">

        {# Mezzanine CMS styling, not sure what this is for exactly, maybe admin pages and CMS functionality #}
        {#        <link rel="stylesheet" href="{% static "css/mezzanine.css" %}">#}

        {# not sure what this does, commenting out for the moment #}
        {#<link rel="stylesheet" href="{% static "hes/css/bootstrap-theme.css" %}">#}
        {% if LANGUAGE_BIDI %}
            <link rel="stylesheet" href="{% static "hes/css/bootstrap-rtl.css" %}">
        {% endif %}
        {% ifinstalled cartridge.shop %}
            <link rel="stylesheet" href="{% static "css/cartridge.css" %}">
            {% if LANGUAGE_BIDI %}
                <link rel="stylesheet" href="{% static "css/cartridge.rtl.css" %}">
            {% endif %}
        {% endifinstalled %}
        {% block extra_css %}{% endblock %}

    {% endcompress %}

    {% compress js %}
        <script src="{% static "hes/js/jquery/1.11.3/jquery-1.11.3.min.js" %}"></script>
    {% endcompress %}

    <!--[if lt IE 9]>
<script src="{% static "js/html5shiv.js" %}"></script>
<script src="{% static "hes/js/respond.min.js" %}"></script>
<![endif]-->

    {% block extra_head %}{% endblock %}

</head>
<body id="{% block body_id %}body{% endblock %}">

<div id="wrapper">

    {% block header_container %}
        <div class="header">
            <nav class="navbar   navbar-site navbar-default" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle"
                                type="button">
                            <span class="sr-only">{% trans "Toggle Navigation" %}</span> <span class="icon-bar"></span> <span
                                class="icon-bar"></span> <span class="icon-bar"></span></button>
                        <a href="{% url "home" %}" class="navbar-brand logo logo-title">
                            <!-- Original Logo will be placed here  -->
                        <img src="{% static "hes/images/logo.png" %}"/>
                        </a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">
                            {% if request.user.is_authenticated %}
                                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <span>Hello, {% user_display user %}</span> <i class="icon-user fa"></i> <i
                                        class=" icon-down-open-big fa"></i></a>
                                    <ul class="dropdown-menu user-menu">
                                        <li class="active"><a href="{% url "hes:account-home" %}"><i class="icon-home"></i>
                                            Personal Home </a></li>
                                        <li><a href="{% url "account_logout" %}">Signout <i
                                                class="glyphicon glyphicon-off"></i> </a></li>
                                    </ul>
                                </li>

                            {% else %}
                                <li><a href="{% url "account_login" %}">{% trans "Login" %}</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <!--/.nav-collapse -->
                </div>
                <!-- /.container-fluid -->
            </nav>
        </div>
        <!-- /.header -->
    {% endblock header_container %}

    {% block body_container %}
    {% endblock body_container %}

    {% block footer_container %}
        <div class="footer" id="footer">
            <div class="container">
                <ul class=" pull-left navbar-link footer-nav">
                    <li><a href="/"> Home </a> <a href="{% url "hes:about-us" %}"> About us </a> <a
                            href="{% url "hes:coming-soon" %}"> Terms and
                        Conditions </a> <a href="{% url "hes:coming-soon" %}"> Privacy Policy </a> <a
                            href="{% url "hes:contact" %}"> Contact us </a> <a
                            href="{% url "hes:faq" %}"> FAQ </a>
                </ul>
                <ul class=" pull-right navbar-link footer-nav">
                    <li> &copy; 2015 Home Education Supply, LLC</li>
                </ul>
            </div>

        </div>
        <!-- /.footer -->
    {% endblock footer_container %}

</div>
<!-- /.wrapper -->


{# Placed at the end of the document so the pages load faster #}
{% compress js %}
    <!-- include checkRadio plugin //Custom check & Radio  -->
    <script type="text/javascript" src="{% static "hes/js/icheck.min.js" %}"></script>

    <script type="text/javascript" src="{% static "hes/bootstrap/js/bootstrap.min.js" %}"></script>

    <!-- include carousel slider plugin  -->
    <script type="text/javascript" src="{% static "hes/js/owl.carousel.min.js" %}"></script>

    <!-- include equal height plugin  -->
    <script type="text/javascript" src="{% static "hes/js/jquery.matchHeight-min.js" %}"></script>

    <!-- include jquery list shorting plugin plugin  -->
    <script type="text/javascript" src="{% static "hes/js/hideMaxListItem.js" %}"></script>

    <!-- include jquery.fs plugin for custom scroller and selecter  -->
    <script type="text/javascript" src="{% static "hes/plugins/jquery.fs.scroller/jquery.fs.scroller.js" %}"></script>
    <script type="text/javascript" src="{% static "hes/plugins/jquery.fs.selecter/jquery.fs.selecter.js" %}"></script>


    <!-- include custom script for site  -->
    <script type="text/javascript" src="{% static "hes/js/script.js" %}"></script>

    <!-- include jquery autocomplete plugin  -->

    <script type="text/javascript" src="{% static "hes/plugins/autocomplete/jquery.mockjax.js" %}"></script>
    <script type="text/javascript" src="{% static "hes/plugins/autocomplete/jquery.autocomplete.js" %}"></script>
    <script type="text/javascript" src="{% static "hes/plugins/autocomplete/usastates.js" %}"></script>

    <script type="text/javascript" src="{% static "hes/plugins/autocomplete/autocomplete-demo.js" %}"></script>

    <!-- include form-validation plugin || add this script where you need validation   -->
    <script type="text/javascript" src="{% static "hes/js/form-validation.js" %}"></script>
    <script src="{% static "hes/js/pace.min.js" %}"></script>

    <script src="{% static "hes/js/footable.js" %}" type="text/javascript"></script>
    <script src="{% static "hes/js/footable.filter.js" %}" type="text/javascript"></script>


{% endcompress %}

{% block extra_js %}{% endblock %}

<script>
    paceOptions = {
        elements: true
    };
</script>

{% include "includes/footer_scripts.html" %}

</body>
</html>

hes/templates/hes/coming-soon.html
{% extends "hes/base.html" %}
{% load i18n %}

{% block meta_title %}{% trans "Coming Soon!" %}{% endblock %}

{% block body_container %}
    <div class="container">
        <h1>Coming Soon</h1>
    </div>
{% endblock body_container %}

hes/users/templates/users/user_form.html
{% extends "hes/base.html" %}
{% load crispy_forms_tags %}

{% block title %}User: {{ user.username }}{% endblock %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1>{% block header %}User: {{ user.username }}{% endblock %}</h1>
            <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="control-group">
                  <div class="controls">
                    <button type="submit" class="btn">Update</button>
                  </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

hes/users/templates/users/user_list.html
{% extends "hes/base.html" %}
{% load static %}{% load i18n %}
{% block title %}Members{% endblock %}

{% block content %}

<div class="container">

  <div class="row">
    <div class="col-xs-12">
      <h2>Users</h2>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="list-group">
          {% for user in user_list %}
            <a href="{% url 'users:detail' user.username %}" class="list-group-item">
              <h4 class="list-group-item-heading">{{ user.username }}</h4>
              <p class="list-group-item-text">{{ maker.tagline }}</p>
            </a>
          {% endfor %}

      </div>
    </div>
  </div>

</div>

{% endblock content %}